### ISSUE TITLE
Ablation KeyError

### ISSUE THREAD

**Issue by shukon** [automl/CAVE#122]
Every one in a while I run into the following error. Not perfectly reproducable, though. @AndreBiedenkapp any ideas?

```
INFO:Ablation:Difference in source and target: 18
Traceback (most recent call last):
  File "scripts/cave.py", line 17, in <module>
    cave.main_cli()
  File "/home/shuki/Documents/CAVE/cave/cave_cli.py", line 127, in main_cli
    feature_analysis=feature_analysis)
  File "/home/shuki/Documents/CAVE/cave/cavefacade.py", line 319, in analyze
    incneighbor='incneighbor' in param_importance)
  File "/home/shuki/Documents/CAVE/cave/cavefacade.py", line 376, in parameter_importance
    self.output)
  File "/home/shuki/Documents/CAVE/cave/analyzer.py", line 464, in parameter_importance
    result = self.pimp.evaluate_scenario([modus], save_folder)
  File "/home/shuki/virtenv/vespy/src/pimp/pimp/importance/importance.py", line 484, in evaluate_scenario
    dict_[method] = self.evaluator.run()
  File "/home/shuki/virtenv/vespy/src/pimp/pimp/evaluator/ablation.py", line 313, in run
    modifiable_config_dict = self._check_children(modifiable_config_dict, candidate_tuple)
  File "/home/shuki/virtenv/vespy/src/pimp/pimp/evaluator/ablation.py", line 217, in _check_children
    if self.source_active[child] and not self.target_active[child]:
KeyError: 'sp-clause-inversion'
```

**Comment by AndreBiedenkapp** [comment]
This is an issue for PIMP.
Looks like this might happen when a child parameter (in this case sp-clause-inversion) is not active in the source but in the target. I'll get a quick fix for that in PIMP

**Comment by shukon** [comment]
Thanks :)
