### ISSUE TITLE
NameError: name 'incumbent' is not defined when using with BOHB

### ISSUE THREAD

**Issue by ashraaghav** [automl/CAVE#229]
I am using CAVE with BOHB, having forbidden clauses in configuration space. Since there was an issue in the master/pypi version of PyImp for forbidden clauses, I had to install the dev version (link below).

But now CAVE is throwing the following error:

    ERROR:cave.cavefacade.CAVE:name 'incumbent' is not defined
    Traceback (most recent call last):
      File "/media/ashwin/OS/Users/Ashwin/Documents/My Documents/MS/Freiburg/2018-WS/ML4AAD/ml4aad-project/ml4aad_ws18_project/CAVE/cave/cavefacade.py", line 100, in wrap
        analyzer = f(self, cave, *args, **kw)
      File "/media/ashwin/OS/Users/Ashwin/Documents/My Documents/MS/Freiburg/2018-WS/ML4AAD/ml4aad-project/ml4aad_ws18_project/CAVE/cave/cavefacade.py", line 876, in local_parameter_importance
        lpi = LocalParameterImportance(cave.pimp, cave.incumbent, cave.output_dir)
      File "/media/ashwin/OS/Users/Ashwin/Documents/My Documents/MS/Freiburg/2018-WS/ML4AAD/ml4aad-project/ml4aad_ws18_project/CAVE/cave/analyzer/local_parameter_importance.py", line 24, in __init__
        self.parameter_importance("lpi")
      File "/media/ashwin/OS/Users/Ashwin/Documents/My Documents/MS/Freiburg/2018-WS/ML4AAD/ml4aad-project/ml4aad_ws18_project/CAVE/cave/analyzer/cave_parameter_importance.py", line 40, in parameter_importance
        self.pimp.evaluate_scenario([modus], self.output_dir)
      File "/media/ashwin/OS/Users/Ashwin/Documents/My Documents/MS/Freiburg/2018-WS/ML4AAD/ml4aad-project/ml4aad-env/lib/python3.6/site-packages/pimp/importance/importance.py", line 500, in evaluate_scenario
        dict_[self.evaluator.name.lower()] = self.evaluator.run()
      File "/media/ashwin/OS/Users/Ashwin/Documents/My Documents/MS/Freiburg/2018-WS/ML4AAD/ml4aad-project/ml4aad-env/lib/python3.6/site-packages/pimp/evaluator/local_parameter_importance.py", line 230, in run
        mean, var = self._predict_over_instance_set(impute_inactive_values(incumbent))
    NameError: name 'incumbent' is not defined
    Traceback (most recent call last):
      File "cave.py", line 17, in <module>
        cave.main_cli()
      File "/media/ashwin/OS/Users/Ashwin/Documents/My Documents/MS/Freiburg/2018-WS/ML4AAD/ml4aad-project/ml4aad_ws18_project/CAVE/cave/cave_cli.py", line 307, in main_cli
        feature_analysis=feature_analysis)
      File "/media/ashwin/OS/Users/Ashwin/Documents/My Documents/MS/Freiburg/2018-WS/ML4AAD/ml4aad-project/ml4aad_ws18_project/CAVE/cave/utils/timing.py", line 11, in wrap
        result = f(*args, **kw)
      File "/media/ashwin/OS/Users/Ashwin/Documents/My Documents/MS/Freiburg/2018-WS/ML4AAD/ml4aad-project/ml4aad_ws18_project/CAVE/cave/cavefacade.py", line 549, in analyze
        pimp_sort_table_by=pimp_sort_table_by)
      File "/media/ashwin/OS/Users/Ashwin/Documents/My Documents/MS/Freiburg/2018-WS/ML4AAD/ml4aad-project/ml4aad_ws18_project/CAVE/cave/cavefacade.py", line 922, in parameter_importance
        self.local_parameter_importance(d=self._get_dict(d, "Local Parameter Importance (LPI)", run=run), run=run)
      File "/media/ashwin/OS/Users/Ashwin/Documents/My Documents/MS/Freiburg/2018-WS/ML4AAD/ml4aad-project/ml4aad_ws18_project/CAVE/cave/cavefacade.py", line 100, in wrap
        analyzer = f(self, cave, *args, **kw)
      File "/media/ashwin/OS/Users/Ashwin/Documents/My Documents/MS/Freiburg/2018-WS/ML4AAD/ml4aad-project/ml4aad_ws18_project/CAVE/cave/cavefacade.py", line 876, in local_parameter_importance
        lpi = LocalParameterImportance(cave.pimp, cave.incumbent, cave.output_dir)
      File "/media/ashwin/OS/Users/Ashwin/Documents/My Documents/MS/Freiburg/2018-WS/ML4AAD/ml4aad-project/ml4aad_ws18_project/CAVE/cave/analyzer/local_parameter_importance.py", line 24, in __init__
        self.parameter_importance("lpi")
      File "/media/ashwin/OS/Users/Ashwin/Documents/My Documents/MS/Freiburg/2018-WS/ML4AAD/ml4aad-project/ml4aad_ws18_project/CAVE/cave/analyzer/cave_parameter_importance.py", line 40, in parameter_importance
        self.pimp.evaluate_scenario([modus], self.output_dir)
      File "/media/ashwin/OS/Users/Ashwin/Documents/My Documents/MS/Freiburg/2018-WS/ML4AAD/ml4aad-project/ml4aad-env/lib/python3.6/site-packages/pimp/importance/importance.py", line 500, in evaluate_scenario
        dict_[self.evaluator.name.lower()] = self.evaluator.run()
      File "/media/ashwin/OS/Users/Ashwin/Documents/My Documents/MS/Freiburg/2018-WS/ML4AAD/ml4aad-project/ml4aad-env/lib/python3.6/site-packages/pimp/evaluator/local_parameter_importance.py", line 230, in run
        mean, var = self._predict_over_instance_set(impute_inactive_values(incumbent))
    NameError: name 'incumbent' is not defined

* CAVE version = 1.1.4 (master)
* PyImp version = 1.0.6.dev0 (development branch [98-lpi-error-on-forbidden-conditional](https://github.com/automl/ParameterImportance/tree/issue/98-lpi-error-on-forbidden-conditional))

**Comment by shukon** [comment]
Hey :) this should be fixed for now - please note, however, that the dev-branch is under construction still until we found a valid solution to the forbidden-clauses-issue. I'll close since this specific error shouldn't occur anymore, feel free to reopen if it does.
